# Generated by Django 3.2.3 on 2021-05-17 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=250)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.png', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english', models.CharField(max_length=250)),
                ('thai', models.CharField(max_length=250)),
                ('audio', models.FileField(upload_to='')),
                ('image', models.ImageField(default='default.png', upload_to='')),
                ('unit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='units.unit')),
            ],
        ),
    ]
