# Generated by Django 3.2.3 on 2021-05-17 16:11

from django.db import migrations, models
import units.models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='image',
            field=models.ImageField(default='default.png', upload_to=units.models.get_upload_path),
        ),
    ]
