# Generated by Django 3.2.3 on 2021-05-18 10:11

from django.db import migrations, models
import units.models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_alter_unit_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='transliteration',
            field=models.CharField(default='none', max_length=250),
        ),
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.FileField(upload_to=units.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='word',
            name='image',
            field=models.ImageField(default='default.png', upload_to=units.models.get_upload_path),
        ),
    ]
