# Generated by Django 3.2.3 on 2021-05-18 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0003_auto_20210518_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='unit',
        ),
    ]
