# Generated by Django 3.2.3 on 2021-05-18 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_rename_name_unit_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='unit',
            new_name='unit_name',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='unit',
            new_name='unit_name',
        ),
    ]
